export const users = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    username: '@rajesh_kumar',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh',
    bio: 'CSE Student | Guitar Enthusiast | Always up for coffee',
    location: 'Solan Campus',
    joined: 'Sept 2023',
    following: 145,
    followers: 892,
  },
  {
    id: 2,
    name: 'Asmi',
    username: '@asmi_arts',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=asmi',
    bio: 'Artist | Videographer | Creative Content Creator',
    location: 'Solan Campus',
    joined: 'Aug 2022',
    following: 234,
    followers: 567,
  },
  {
    id: 3,
    name: 'Vidya',
    username: '@vidya_codes',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vidya',
    bio: 'Python Enthusiast | Teaching & Learning',
    location: 'Solan Campus',
    joined: 'Jan 2023',
    following: 89,
    followers: 345,
  },
  {
    id: 4,
    name: 'Arjun Singh',
    username: '@arjun_singh',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun',
    bio: 'Mathematics Major | Tutor | Study Group Organizer',
    location: 'Solan Campus',
    joined: 'Jun 2023',
    following: 112,
    followers: 298,
  },
  {
    id: 5,
    name: 'Priya Sharma',
    username: '@priya_sharma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    bio: 'Business Student | Event Coordinator',
    location: 'Solan Campus',
    joined: 'July 2023',
    following: 178,
    followers: 612,
  },
];

export const posts = [
  {
    id: 1,
    userId: 2,
    type: 'request',
    title: 'Looking for a student editor',
    description: 'Looking for a student editor who can help me with my vlogging assignment! I have about 30 mins of footage that needs to be cut down to a 5-min story. Willing to pay or trade for graphic design work!',
    tags: ['#videoediting', '#vlog', '#helpwanted'],
    likes: 24,
    comments: 5,
    shares: 1,
    timeAgo: '2h ago',
    color: 'champagne-pink',
  },
  {
    id: 2,
    userId: 3,
    type: 'offer',
    title: 'Python tutoring sessions',
    description: 'Anyone struggling with CS101 assignments? I\'m offering tutoring sessions this weekend at the library. We can go over Python basics and loops.',
    tags: ['#computerscience', '#tutoring', '#python'],
    likes: 45,
    comments: 12,
    shares: 3,
    timeAgo: '4h ago',
    color: 'moss-green',
  },
  {
    id: 3,
    userId: 4,
    type: 'question',
    title: 'Best study spots on campus?',
    description: 'Hi everyone! New student here. Can someone suggest the best quiet study spots on campus? Preferably with good wifi and comfortable seating.',
    tags: ['#studytips', '#campus', '#newstudent'],
    likes: 67,
    comments: 23,
    shares: 5,
    timeAgo: '6h ago',
    color: 'tan',
  },
  {
    id: 4,
    userId: 5,
    type: 'social',
    title: 'Cultural Fest Planning Committee',
    description: 'Join our committee to plan Shoolini\'s annual cultural festival! We\'re looking for event coordinators, designers, and volunteers. Meeting this Saturday at the Student Center.',
    tags: ['#culturaltest', '#events', '#volunteerneeded'],
    likes: 89,
    comments: 31,
    shares: 12,
    timeAgo: '8h ago',
    color: 'blood-red',
  },
  {
    id: 5,
    userId: 1,
    type: 'request',
    title: 'Lost hostel keys',
    description: 'Has anyone seen my hostel keys? Lost them somewhere between the library and Block C. They have a red keychain. Please let me know if you find them!',
    tags: ['#lostandfound', '#hostel', '#help'],
    likes: 12,
    comments: 3,
    shares: 1,
    timeAgo: '10h ago',
    color: 'champagne-pink',
  },
];

export const categories = [
  { title: 'Freelancers', color: 'champagne-pink' },
  { title: 'Study Groups', color: 'blood-red' },
  { title: 'Social Events', color: 'moss-green' },
  { title: 'Lost & Found', color: 'tan' },
];

export const trendingTags = [
  '#videoediting',
  '#calculus',
  '#gymbuddy',
  '#lostandfound',
  '#python',
  '#design',
  '#tutoring',
  '#roommate',
];

export const topContributors = [
  { name: 'Rajesh Kumar', username: '@rajesh_kumar', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh', id: 1 },
  { name: 'Priya Sharma', username: '@priya_sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya', id: 5 },
  { name: 'Vidya', username: '@vidya_codes', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vidya', id: 3 },
];
